### ISSUE TITLE
Load repeated SVGs once

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#104]
![screen shot 2017-01-28 at 17 25 04](https://cloud.githubusercontent.com/assets/5931528/22398363/d1a397e2-e57e-11e6-87f3-ceb5ae206b00.png)

The social SVGs are inlined multiple times on the page, leading to a lot of unnecessary HTML repetition. It would be good to find a way of loading these only once (preferably inlining them), and [linking to them with a `<use>` element](https://css-tricks.com/svg-use-with-external-reference-take-2/) wherever they are used.

I'm not sure how this approach will interact with the `gulp-inline` plugin that we are using to inline our SVGs.

**Comment by SiAdcock** [comment]
@chrisgeary92 Have you thought of a simple way of solving this issue? I'm sort of part way towards creating my own Gulp plugin to do the deduping based on path `id`, but if you can think of a simpler way, please let me know!

**Comment by crgeary** [comment]
I'm not too sure how to integrate it into the site, but [this package](https://www.npmjs.com/package/gulp-svg-symbols) seems to do 50% of the work, and [this package](https://github.com/klei/gulp-inject#injecting-files-contents) maybe does the other 50% of the work. I've never used either of the packages, and unfortunately have no time until Tuesday to try them out.

I'd be interested to see what you come up with, I'm happy to try the above, but wouldn't till be the middle of next week-ish.

**Comment by SiAdcock** [comment]
Top stuff, thanks man. I was effectively reinventing gulp-svg-symbols in a crude way! I shall have a play if I find time today

**Comment by SiAdcock** [comment]
As discovered in #143, reusing SVGs does not reduce page weight in practice. Thanks Gzip!
