### ISSUE TITLE
Add background-color to .hero-header

### ISSUE THREAD

**Issue by crgeary** [WDOTS/wdots.github.io#111]
Currently, if for some reason the image doesn't load in, or if the user has a slow connection and they're waiting on the large hero-header image, they're presented with a white screen.

![screen shot 2017-02-11 at 12 09 16](https://cloud.githubusercontent.com/assets/3949335/22853598/f3313b38-f052-11e6-917c-eecaaa6ab50f.png)

Which wouldn't be a big problem, but the text is also white.. Adding a background colour to `.hero-header` would solve this.

A possible colour option: `#234823`, which looks like this: 

![screen shot 2017-02-11 at 12 14 45](https://cloud.githubusercontent.com/assets/3949335/22853632/b493d65a-f053-11e6-8263-a185b27ff138.png)

**Comment by SiAdcock** [comment]
Great idea, @chrisgeary92. I was trying to think of ways we could get the request for the woods image to kick off earlier, but it's complicated by the srcset. Your suggestion will at least fix the main UX problem

**Comment by crgeary** [comment]
@SiAdcock could use `<link rel="prefetch" href="">`.

Do you know if you can use `media=""` attributes on these? It's wasteful to prefetch every image, but maybe clever use of the media attribute could help us conditionally prefetch based on browser width?

**Comment by SiAdcock** [comment]
It's an interesting idea, worth experimenting! The less than ideal alternative is to use JavaScript, but I'd rather use native HTML features where possible.
