### ISSUE TITLE
Horizontal scroll on mobile

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#116]
Since we said goodbye to Bootstrap (#103) there has been a horizontal scroll on mobile devices.

![screen shot 2017-02-19 at 13 28 44](https://cloud.githubusercontent.com/assets/5931528/23102777/5d1f2cd0-f6a7-11e6-904a-9745346d3319.png)

A scrollbar is not visible on the devices I have tested (iPhone SE, iPhone 6S+), but the scroll functionality is present. It would be great to get rid of this behaviour.

**Comment by crgeary** [comment]
It's `.speaker` that's causing the issue, has a `margin-right` at mobile, which combined with the `width: 100%` pushes it out.

**Comment by SiAdcock** [comment]
Good debugging @chrisgeary92 💎 💎 💎

**Comment by crgeary** [comment]
Chrome has made debugging too easy now. It's almost not a challenge anymore 😂  😂
