### ISSUE TITLE
Image file size needs to be reduced

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#12]
Image size is by far the biggest performance bottleneck on the site. We should aim to reduce the file size of the `woods.jpg` background image and the profile pictures by at least half.

**Comment by jamesadarich** [comment]
I no longer be using the mi

**Comment by SiAdcock** [comment]
Wha-?

@jamesrichford

**Comment by jamesadarich** [comment]
I have no idea what this is, pocket GitHub replying? Haha sorry mate

**Comment by SiAdcock** [comment]
But... but it seemed like you were about to say something awesome about compression! Put your phone back in your pocket and jiggle it around, let it finish what it was telling us.

**Comment by jamesadarich** [comment]
Hahaha I'll give it a go. Been seeing a lot of activity on here by the way,
need any help? :)

**Comment by SiAdcock** [comment]
Always, @jamesrichford! Feel free to fix an issue if you like 😄  

I'm going to start work on a build process soon, so this will need defining and implementing.

If you can think of anything we need, raise an issue and we can start adding more features.

**Comment by SiAdcock** [comment]
Fixed by #31
