### ISSUE TITLE
Huge footer in Safari

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#123]
Looks a bit 😖 

**Desktop**

<img width="1319" alt="screen shot 2017-03-11 at 09 25 13" src="https://cloud.githubusercontent.com/assets/5931528/23822077/c4cdd26a-063c-11e7-9107-5e0fd7c96e7d.png">

**Mobile**

<img width="323" alt="screen shot 2017-03-11 at 09 27 47" src="https://cloud.githubusercontent.com/assets/5931528/23822088/0506afe6-063d-11e7-9e08-1ea08c6c9186.png">

**Comment by crgeary** [comment]
Huge footers used to be quite popular 👍  🙃
