### ISSUE TITLE
Incorrect font on desktop Safari

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#129]
We are seeing the wrong font on desktop Safari 10

<img width="838" alt="screen shot 2017-03-18 at 18 04 05" src="https://cloud.githubusercontent.com/assets/5931528/24074690/6390e07c-0c05-11e7-8cb6-4f8778f6b7ba.png">

This is not happening on iOS Safari

**Comment by crgeary** [comment]
Cool, most likely because we only have `woff2` fonts, Safari needs `woff`.

Where did you get the current `woff2` font from, did you pinch it from Google Fonts? If yes, where did you get the `dosis-latin-ext` copy, can only work how to get the main font.

**Comment by SiAdcock** [comment]
Nice one @chrisgeary92 

@jimmynames do you remember where you found the font? Would be good to get the same one in woff format

**Comment by crgeary** [comment]
I found the font, you can grab a copy from [Google Fonts](https://fonts.google.com/specimen/Dosis), just found the Latin Extended version does exist on there.

So should be able to grab the `woff` version from them to load in for Safari.
