### ISSUE TITLE
Fix Sass Lint warnings

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#150]
We have a whole bunch of Sass Lint warnings. They are currently hidden, but you can see them if you run `sass-lint` with the `--verbose` option:

```bash
$ ./node_modules/.bin/sass-lint  --no-exit --verbose
```

Any help in clearing these warnings would be appreciated! I'd suggest identifying a warning that crops up a lot and raising a PR to fix that warning.

To fix a warning, you can either:

- Fix the SCSS code that generates the warning
- [Disable the rule](https://github.com/sasstools/sass-lint#disabling-linters-via-source) if you think the rule is okay, but doesn't apply in a particular context
- Modify the config file if you think the warning is not something we should lint against

**Comment by crgeary** [comment]
If you're curious how often a particular rule crops up, you can do:

```
./node_modules/.bin/sass-lint --no-exit --verbose | grep "YOURSEARCH" | wc -l
```

Where`YOURSEARCH` is the relevant string to search for in the lint output.
