### ISSUE TITLE
About us layout broken in iPhone 4

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#17]
![picture 32](https://cloud.githubusercontent.com/assets/5931528/16731707/7e5a80f6-4771-11e6-980b-afe3ffba6b29.png)

**Comment by jamesryan-dev** [comment]
💪🏻 easy peasy

**Comment by jamesryan-dev** [comment]
lol

**Comment by SiAdcock** [comment]
TBH I think we can close this and raise a different issue for mobile UX. You've fixed the clear display issue described here
