### ISSUE TITLE
Improve above-the-fold UX on mobile

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#19]
Currently this is how the home page looks above-the-fold on iPhone:
## iPhone 4

![picture 33](https://cloud.githubusercontent.com/assets/5931528/16769536/08f0d308-4841-11e6-99cd-95247d7137c7.png)

Title cuts off at the bottom
## iPhone 5

![picture 34](https://cloud.githubusercontent.com/assets/5931528/16769530/00232294-4841-11e6-9175-fdde9bbb6793.png)

Description cuts off at the bottom

It would be ideal if the appearance on all mobile devices could take after how cleanly it appears on iPhone 6:

![picture 35](https://cloud.githubusercontent.com/assets/5931528/16769593/4727935a-4841-11e6-87a5-7c456c625fa3.png)

**Comment by jamesryan-dev** [comment]
Added custom media queries at end of css if you feel this isnt sufficient open issue again :) 👍
