### ISSUE TITLE
Define and implement a build and deployment process

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#20]
# Build
- [x] Concatenate and minify all the page JavaScript
- [x] Create JavaScript source maps
- [x] Minify all the page CSS
- [x] Create CSS source maps
- [X] Build HTML from a template
- [x] Inject DEV- and PROD-specific paths into HTML template
# Continuous Integration
- [x] Create new default branch called `integration`. All code will be merged into `integration`. Protect from force pushes
- [x] Set up Travis account
- [x] Run lint task when PR is created
- [x] Ensure branch is up to date with `integration` when a PR is created
# Deployment

When code is merged into `integration`, it will kick off a job in Travis CI. This job will run a script that does the following:
1. clones the repo onto the CI server
2. checks out the integration branch
3. runs the build
4. merges the built code into master
5. pushes the master branch to GitHub

There is a gist of a script we can use here:

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by SiAdcock** [comment]
At the moment, we are serving all our JS and CSS unminified in individual files. It would be beneficial if we can automatically minify and concatenate them

**Comment by SiAdcock** [comment]
# Deployment process proposal

GitHub pages is served from the `master` branch of the `wdots.github.io` repo. This poses an interesting question as to how to get built code (minified JS, CSS and HTML) onto the `master` branch. I think we ought to avoid checking built code into GitHub if we can help it.

My suggestion is this: we create a new branch called `integration` into which we will merge our code.

When code is merged into `integration`, it will kick off a job in a Continuous Integration tool such as Travis CI. This job will run a script that does the following:
1. clones the repo onto the CI server
2. checks out the integration branch
3. runs the build
4. merges the built code into master
5. pushes the master branch to GitHub

There is a gist of a script we can use here:

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

We will no longer merge into `master`. In fact that branch will be locked to prevent accidental commits. In the future we will only merge into `integration`

Does anyone have any thoughts on this?

**Comment by Jameskmonger** [comment]
This is great @SiAdcock :smile: Really smooth

**Comment by SiAdcock** [comment]
😄 

So far so good!
