### ISSUE TITLE
Add to Calendar dropdown partially hidden

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#38]
Due to the `overflow: hidden` on the `.hero-header`, the calendar dropdown is partially hidden

![screen shot 2016-07-30 at 10 25 29](https://cloud.githubusercontent.com/assets/5931528/17269433/196dd2d2-5640-11e6-8eec-752783e3921b.png)

**Comment by CarlosMela** [comment]
Also the dropdown width is smaller than the button one.

**Comment by CarlosMela** [comment]
Solved increasing the separation needed for the dropdown between the button and the next section 'About us'. Maybe other design is needed to find a better solution and avoid the overflow: hidden problem.
