### ISSUE TITLE
Responsive image srcset looks incorrect on certain devices

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#47]
## iPad landscape

CSS dimensions: 1024 x 768
Pixel density: 2x
Served image: woods-3x.jpg

![screen shot 2016-07-31 at 15 50 24](https://cloud.githubusercontent.com/assets/5931528/17277266/84225818-5736-11e6-809d-a071593c9d98.png)
## Samsung Galaxy S6

![screenshot_20160731-145815](https://cloud.githubusercontent.com/assets/5931528/17277270/a562a1ea-5736-11e6-8b5b-c1d57116052d.png)

**Comment by SiAdcock** [comment]
I'm going to close this, @CarlosMela, but can you let me know how it looks on the Samsung Galaxy S6 as I have no adequate means of testing this. If it still looks bad, we can re-open this issue

**Comment by Jameskmonger** [comment]
Looks good when emulating @SiAdcock ![wdots galaxy s6 emulated](http://i.imgur.com/sxzgYaa.png)

**Comment by SiAdcock** [comment]
Thanks @Jameskmonger. Are you using a super-up-to-date version of Chrome or something? I don't get the option to emulate the Galaxy S6.

**Comment by Jameskmonger** [comment]
Nope @SiAdcock, I set it up as a custom device :iphone: 

Width: `640`
Height: `360`
Device pixel ratio: `4`
User agent string:  `Mozilla/5.0 (Linux; Android 5.1.1; SM-G925F Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/47.0.2526.100 Mobile Safari/537.36`

**Comment by SiAdcock** [comment]
Awesome! Where did you get the numbers from?

**Comment by Jameskmonger** [comment]
- http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand807868/samsung-galaxy-s6-edge
- http://www.canbike.org/CSSpixels/

**Comment by SiAdcock** [comment]
Top stuff, @Jameskmonger! I'm bookmarking the crap out of that CSS Pixels site 💎 🔖
