### ISSUE TITLE
Remove unused CSS

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#50]
According to Chrome dev tools's web page performance audit, 31% of the rules in `style.css` are not being used. 

In the long term, it would be useful to refactor the CSS, removing these rules in the process. However, in the short term, we could automatically remove unused CSS rules as part of the build process.

One tool we could look into is [UnCSS](https://github.com/giakki/uncss)

**Comment by SiAdcock** [comment]
- [x] Removed unused rules in style.css
- [x] Remove unused Bootstrap rules

**Comment by jamesryan-dev** [comment]
I'd like to help with this
- maybe pair?
🤔

**Comment by SiAdcock** [comment]
Yeah man, for sure! According to a Chrome dev tool audit, we're not using 96%(!!) of it. Maybe we can roll our own bits that we are using, then throw Bootstrap out entirely.

**Comment by Jameskmonger** [comment]
That would be best @SiAdcock! Identify what we need and bin the rest. Might be a feature in Chrome to automatically pull out what we use?

**Comment by SiAdcock** [comment]
I think UnCSS does that. Chrome does the opposite and identifies what you're not using!

It's likely that we are mostly using a few grid column sizes, a bunch of reset styles provided by normalise, as well as some button and container styling.

If you know of any good alternative lightweight grid systems, let me know and we can start migrating over

**Comment by crgeary** [comment]
For a laugh more than anything -> https://github.com/Heydon/fukol-grids
