### ISSUE TITLE
Get Google PageSpeed score up to 75

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#73]
We should try aim for a PageSpeed Insights score of 75/100 on both Desktop and Mobile.

![](http://i.imgur.com/tNWODtf.jpg)

https://developers.google.com/speed/pagespeed/insights/?url=WDOTS.github.io&tab=mobile

**Comment by crgeary** [comment]
Just took a look at the current score, 64 Mobile, 81 Desktop. There isn't much we can easily fix due to caching restrictions on Github pages.

We're at the mercy of third party services :(

I was trying to figure out how we could improve the score while using Github pages, and I had these ideas (and many others, but these are the main ones):

### 1. Leverage browser caching

We could inline all, or some of the SVG's into the markup. This currently scores in the red because there are a lot of them, if we did only a few we would likely knock it down to orange which boosts the score slightly.. But most importantly we could reduce the number HTTP requests, and decrease the number of assets with low caching times by inlining them. The site is super-small, so there is no real issue with bloat IMO.

There is a cool way with SVG's to re-use groups of paths, so you don't have to inline the github/twitter/linkedin icons for every person on the site. Just needs to be added once, and then reference it with `<use>`

### 2. Enable compression

The https://addtocalendar.com/ scripts/styles are bringing this down because they don't have GZIP. I emailed them to ask if they could enable GZIP (I don't think they know they're not using it).

The next option would be to host locally.

* * *

Thoughts?

**Comment by SiAdcock** [comment]
Agreed on both points @chrisgeary92 

Inlining SVGs is definitely something we should be doing. We could probably add a step to the HTML build task that can replace references to `<img="*.svg">` with the contents of the SVG file (I've implemented this approach in #82) But I'm open to the `<use>` idea too if you fancy raising a PR!

Add to Calendar assets are a bit of a disaster. I've started addressing them in #80. Feel free to give this a quick review if you have time 😄 

To further improve the score, we could look for a third party asset hosting service which would give us more control over caching. I'd rather not pay for a service just for this site, so if anyone knows of any free services, let me know!

**Comment by Jameskmonger** [comment]
My personal site (http://jamesmonger.com) is at 71/100 for mobile and 89/100 for desktop @SiAdcock and it's using AMP with no images. Not sure we'll be able to hit 75/100 for mobile as @chrisgeary92 said.

**Comment by crgeary** [comment]
We could definitely do it (challenges are fun). I just pushed up a site yesterday that hits 91/100 for mobile (https://wheretoskate.firebaseapp.com/), if I inline the CSS (as there isn't much) it'll probably be 100.. Granted the site is smaller than WDOTS and your own, but PSI doesn't care about speed/size, only if you meet their best practice rules.

@Jameskmonger With your site, it looks like you have only github/stackoverflow icons. If you remove font-awesome and replace those with inline SVGs you'll probably hit 75.

**Comment by Jameskmonger** [comment]
Working on phasing out the icons at the moment @chrisgeary92 ;)

**Comment by SiAdcock** [comment]
PageSpeed considers the version of [`jquery-easing`](https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js) we are using to be unminified, which is probably costing us a point or two.

We should use an alternative CDN for this, such as [unpkg.com](https://unpkg.com), which features a more [heavily minified](https://unpkg.com/jquery-easing@0.0.1/dist/jquery.easing.1.3.umd.min.js) version of the file.

**Comment by crgeary** [comment]
Could use unpkg.com for all assets (if possible), keeps the number of hosts the browser has to resolve to a minimum, less certificates need parsing, and less DNS lookups have to be made if everything comes from the same place :)

Doesn't help google page speed, but is good for performance either way :)

**Comment by SiAdcock** [comment]
Love it, great insight dude

**Comment by SiAdcock** [comment]
We could probably go _even further_ with the DNS lookup optimisation by using [DNS prefetching](https://css-tricks.com/prefetching-preloading-prebrowsing/#article-header-id-0)

**Comment by crgeary** [comment]
Yes.. Further is faster! It's a shame we cannot set HTTP headers, and do it there.. For another time I guess!

**Comment by SiAdcock** [comment]
Do you have an example / article explaining how we might do it with HTTP headers?

**Comment by crgeary** [comment]
Ah, no that was me mixing up preloading of assets with prefetching DNS.. That being said, if you were to preload at least 1 asset from unpkg.com in a HTTP header, that would require the browser to resolve the DNS (which would be from a HTTP header). A little hacky, no idea if that works?

**Comment by SiAdcock** [comment]
I don't know how to preload a script in a HTTP header, but feel free to raise a PR and we can run some analysis in dev tools, see if it's faster than preconnecting to the host or prefetching DNS

**Comment by crgeary** [comment]
Oh... It's just like this:

`Link: </some/path/to/asset.js>; rel=preload; as=script`

Spec: https://www.w3.org/TR/preload/

Only works with HTTP/2, and we cannot do with Github Pages :/ To remember for another time, if/when we can do it ;)

I will however raise PR if there isn't one already for the unpkg stuff, just had a busy week :)

**Comment by Jameskmonger** [comment]
Would it not be good for us to bundle all dependencies in a single file and then serve them? The less HTTP requests the better.

**Comment by crgeary** [comment]
I think while we're on github.io, @Jameskmonger is correct, it would be better than the separate requests. If there is a plan to move somewhere with HTTP/2 support then keeping them as separate requests are arguably better than 1 big request due to multiplexing.

**Comment by SiAdcock** [comment]
Yeah, I tend to agree. The dependencies that we're not fetching from unpkg (jquery-visible and addtocalendar) should be bundled into the main.js.

From what I understand, though, unpkg serves its files over HTTP/2, so all of those files will be multiplexed, even if our `index.html` is on github.io. Is my understanding correct?

**Comment by crgeary** [comment]
Yep, I am 99% sure this is the case. Double checked it with someone from a CDN company who also said this would be the case.

**Comment by crgeary** [comment]
We just hit [85/100](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwdots.github.io%2F&tab=desktop)!

In [my comment](https://github.com/WDOTS/wdots.github.io/issues/73#issuecomment-269475860) above, I mentioned I asked AddToCalendar to enable GZIP on their assets. Which they've just done, which has completed another PSI rule for us 👍

**Comment by SiAdcock** [comment]
Awesome @chrisgeary92! I will check later today whether they decided to also minify the CSS.

It would still be preferable to request the assets from unpkg.com, and it looks like they're making moves to update the version of the script that is currently on npm. They probably need help doing this, if anyone wants to volunteer and show them how to set up a CI rig!

**Comment by SiAdcock** [comment]
Oh happy day!

![screen shot 2017-02-11 at 10 44 16](https://cloud.githubusercontent.com/assets/5931528/22853178/191fbb6e-f047-11e6-8b8e-83e266320dbd.png)
