### ISSUE TITLE
Enable HTTPS?

### ISSUE THREAD

**Issue by crgeary** [WDOTS/wdots.github.io#74]
Could we enable HTTPS? There is a [checkbox in the settings](https://github.com/WDOTS/wdots.github.io/settings#pages-https-redirect-feature) that can be checked.

I've tested the website locally with HTTPS and all runs ok! (see below, no mixed content)

![WDOTS Screenshot](http://i.imgur.com/dkYLHNa.png)

Didn't want to just go ahead an check the box, without someone else chipping in, seeing as though I'm a newbie here 😔

**Comment by SiAdcock** [comment]
Wow, I did not know that!

Absolutely tick that box! :+1:

**Comment by crgeary** [comment]
I noticed the development copy uses local assets, but the built site uses CDN URLs, so there's a pull-request for one of the assets: #75
