### ISSUE TITLE
App Manifest.Json

### ISSUE THREAD

**Issue by crgeary** [WDOTS/wdots.github.io#97]
Relates to: #85 

If we're going offline, would also be good to add a manifest with some icons, and app names etc to help anyone that wants to add the site to their homescreen. It currently looks rubbish on Android if you do this.

A manifest.json will allow us to control the [theme colour](https://developers.google.com/web/updates/images/2014/11/theme-color-ss.png) of the browser (if supported), the icon shown on the homescreen and a few other things.

**Comment by SiAdcock** [comment]
Awesome, so progressive! This will also improve our Lighthouse score. Not that we're [benchmark hussies](https://hackernoon.com/10-things-i-learned-making-the-fastest-site-in-the-world-18a0e1cdf4a7#940c) or anything 😉

**Comment by crgeary** [comment]
Indeed.. The current WDOTS site gets 50/100 (for reference) 💡🏠
